apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::775485985055:role/UdacityFlaskDeployCBKubectlRole
      username: build
      groups:
      - system:masters
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::775485985055:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-GU7BW66910Q0
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-03-25T16:49:47Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "5940"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: a2b12e0b-6eb8-11ea-b8e9-0ab16f61f9d2
